name: "Auto Assign"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: twoeqaul0/auto-assign-bot@v1.2.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
